In [1]:
import pandas as pd

In [2]:
students = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha", "Rohit"],
    "Maths": [85, 72, 91, 65, 78],
    "Science": [88, 75, 95, 70, 80],
    "English": [82, 68, 90, 72, 76]
}

df = pd.DataFrame(students)

df

    Name  Maths  Science  English
0  Rahul     85       88       82
1  Priya     72       75       68
2   Aman     91       95       90
3  Sneha     65       70       72
4  Rohit     78       80       76

In [3]:
df["Total"] = df["Maths"] + df["Science"] + df["English"]

df

    Name  Maths  Science  English  Total
0  Rahul     85       88       82    255
1  Priya     72       75       68    215
2   Aman     91       95       90    276
3  Sneha     65       70       72    207
4  Rohit     78       80       76    234

In [4]:
df["Percentage"] = df["Total"] / 3

df

    Name  Maths  Science  English  Total  Percentage
0  Rahul     85       88       82    255   85.000000
1  Priya     72       75       68    215   71.666667
2   Aman     91       95       90    276   92.000000
3  Sneha     65       70       72    207   69.000000
4  Rohit     78       80       76    234   78.000000

In [5]:
def grade(percent):
    
    if percent >= 90:
        return "A+"
    
    elif percent >= 80:
        return "A"
    
    elif percent >= 70:
        return "B"
    
    elif percent >= 60:
        return "C"
    
    else:
        return "F"

df["Grade"] = df["Percentage"].apply(grade)

df

    Name  Maths  Science  English  Total  Percentage Grade
0  Rahul     85       88       82    255   85.000000     A
1  Priya     72       75       68    215   71.666667     B
2   Aman     91       95       90    276   92.000000    A+
3  Sneha     65       70       72    207   69.000000     C
4  Rohit     78       80       76    234   78.000000     B

In [6]:
top_student = df.loc[df["Percentage"].idxmax()]

print("Top Student:")
print(top_student)

Top Student:
Name          Aman
Maths           91
Science         95
English         90
Total          276
Percentage    92.0
Grade           A+
Name: 2, dtype: object

In [7]:
print(df)

    Name  Maths  Science  English  Total  Percentage Grade
0  Rahul     85       88       82    255   85.000000     A
1  Priya     72       75       68    215   71.666667     B
2   Aman     91       95       90    276   92.000000    A+
3  Sneha     65       70       72    207   69.000000     C
4  Rohit     78       80       76    234   78.000000     B

In [8]:
df.to_csv("student_grades.csv", index=False)

print("Results saved successfully!")

Results saved successfully!

In [10]:
from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY")

student_name = input("Enter student name: ")
grade = input("Enter grade: ")

response = client.responses.create(
    model="gpt-5",
    input=f"""
    A student named {student_name} scored grade {grade}.

    Provide:
    1. Performance feedback
    2. Strengths
    3. Areas of improvement
    4. Study tips
    """
)

print(response.output_text)

Enter student name:  Aman
Enter grade:  A+

Here’s tailored feedback for Aman, who earned an A+.

1) Performance feedback
- Exceptional mastery of the curriculum with consistent accuracy and depth.
- Demonstrates strong initiative: asks insightful questions and connects concepts to real-life contexts.
- Produces high-quality work on time; shows academic integrity and attention to detail.
- Participates constructively in class and collaborates well with peers.
- Reflects on learning and adapts strategies effectively.

2) Strengths
- Clear conceptual understanding and strong analytical reasoning.
- Excellent problem-solving and the ability to break down complex tasks.
- Effective communication: explains ideas clearly in writing and discussion.
- Strong time management, organization, and consistent study habits.
- Growth mindset: perseverance, receptiveness to feedback, and steady improvement.
- Balanced approach: detail-oriented while keeping the big picture in view.
- Curiosity and intrinsic motivation to learn beyond requirements.

3) Areas of improvement
- Push beyond the syllabus: tackle extension problems, contests, or mini-research projects.
- Synthesis and transfer: make deeper cross-topic and cross-subject connections.
- Originality: create your own questions, models, or small experiments to test ideas.
- Precision in communication: refine academic writing, citation, and data/graph presentation.
- Leadership and mentoring: guide peers, lead study groups, and share strategies.
- Sustainability: maintain excellence without burnout; build buffers and prioritize recovery.
- Feedback loop: proactively seek critique and iterate on major assignments.

4) Study tips
- Keep doing what works: maintain your current routine and consistency.
- Use active recall and spaced repetition: short, frequent retrieval sessions; build a personal question bank.
- Interleave practice: mix topics and problem types to strengthen transfer and flexibility.
- Error log: track mistakes, categorize them (conceptual vs. careless), and revisit weekly.
- Feynman technique: teach each key concept in simple terms; record or explain to a peer.
- Timed practice: simulate exam conditions; review not just what was wrong, but why.
- Concept maps and summaries: distill each unit to one page of formulas, definitions, and common traps.
- Read beyond the textbook: reputable articles, advanced chapters, or lectures to deepen insight.
- Project-based consolidation: undertake a small capstone or real-world application each term.
- Well-being and focus: 7–9 hours of sleep, movement breaks, and protected “deep work” blocks with minimal distractions.

If you’d like, share Aman’s subject and grade level, and I can tailor the strengths, improvement areas, and study plan even more precisely.

In [11]:
from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY")

student_name = input("Enter student name: ")
grade = input("Enter grade: ")

response = client.responses.create(
    model="gpt-5",
    input=f"""
    A student named {student_name} scored grade {grade}.

    Provide:
    1. Performance feedback
    2. Strengths
    3. Areas of improvement
    4. Study tips
    """
)

print(response.output_text)

Enter student name:  Sneha
Enter grade:  c

1) Performance feedback
Sneha has a solid foundational grasp of the material and can handle familiar tasks. To move into the B/A range, focus on accuracy, deeper explanations, and applying concepts to new or multi‑step problems. With consistent, targeted practice and better test strategies, a higher grade is within reach.

2) Strengths
- Understands core concepts and terminology at a basic level
- Can apply methods to routine or guided problems
- Responds to feedback and shows willingness to improve
- Steady effort when expectations are clear

3) Areas of improvement
- Close conceptual gaps and connect topics, not just memorize steps
- Improve precision and reduce careless errors; show complete reasoning
- Strengthen explanations (use correct terms, evidence, and units)
- Build stamina and timing under test conditions
- Plan work more proactively to avoid last‑minute studying

4) Study tips
- Diagnose: Review graded work and keep an error log (concept, process, or rushing/careless). Rework each error correctly.
- Plan: Set weekly goals (e.g., raise quiz average to 80%) and schedule 3–4 short study blocks across the week.
- Learn actively: Use active recall and spaced repetition (flashcards for key terms/formulas; short self‑quizzes).
- Practice: Mix problem types (interleaving) and “teach back” solutions out loud to confirm understanding.
- Consolidate: After each class, write a 5–7 sentence summary and two questions to clarify next time.
- Test strategy: Do one timed practice weekly; underline command words (explain/compare/derive), allocate time by marks, and leave 5 minutes to check work.
- Get support: Use office hours, tutoring, or a study group; bring your error log to target help.
- If writing‑heavy: Outline first; use claim–evidence–reasoning; revise with the rubric.
- If quantitative: Show every step, annotate formulas with units, draw diagrams, and check answers for reasonableness.
- Focus and wellness: Pomodoro (25/5), minimize phone distractions during study blocks, and aim for 7–8 hours of sleep.

If you share the subject or syllabus topics, I can tailor this further.